version: '3.7'

services:
  ros-master:
    image: ros:melodic-ros-core
    command: roscore
    # forgo the network isolation between container and host
    # will make network.gethostname() use the address of raspberry pi not container
    network_mode: host 
  test-pub:
    build:
      context: ./test_pub
      dockerfile: Dockerfile
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    command: bash -c "source /opt/ros/melodic/setup.bash && python test_pub.py"
    depends_on:
      - ros-master
    network_mode: host 

  server:
    build:
      context: ./cpu_sub
      dockerfile: Dockerfile
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    command: bash -c "source /opt/ros/melodic/setup.bash && python cpu_sub.py"
    depends_on:
      - ros-master
    network_mode: host
