version: '3.7'

services:
  ros-master:
    image: ros:melodic-ros-core
    command: roscore
    # forgo the network isolation between container and host
    # will make network.gethostname() use the address of raspberry pi not container
    network_mode: host 
  cpu-node:
    build:
      context: ./cpu
      dockerfile: Dockerfile
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    command: bash -c "source /opt/ros/melodic/setup.bash && python cpu.py"
    depends_on:
      - ros-master
    network_mode: host 

  server:
    build:
      context: ./ros_nodes
      dockerfile: Dockerfile
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    command: bash -c "source /opt/ros/melodic/setup.bash && python mc_sub.py"
    depends_on:
      - ros-master
    network_mode: host
