version: '3.7'

services:
  ros-master-container:
    image: ros:melodic-ros-core
    command: roscore
    # forgo the network isolation between container and host
    # will make network.gethostname() use the address of raspberry pi not container
    network_mode: host 
  cpu-pi-container:
    build:
      context: ./cpu_pi
      dockerfile: Dockerfile
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    command: bash -c "source /opt/ros/melodic/setup.bash && python cpu.py"
    depends_on:
      - ros-master-container
    network_mode: host 

  bridge-container:
    build:
      context: ./bridge_nodes
      dockerfile: Dockerfile
    environment:
      - "ROS_MASTER_URI=http://localhost:11311"
    command: bash -c "source /opt/ros/melodic/setup.bash && ./run.sh"
    depends_on:
      - ros-master-container
    network_mode: host
    tty: true
